"$schema" = 'https://starship.rs/config-schema.json'

format = '''
$username$directory$git_branch$git_commit$git_state $fill
[\$](bright-green) '''

[username]
show_always = true
style_user = 'bold bright-red'
format = '[$user]($style) '

[directory]
truncation_length = 0
style = 'yellow'

[git_branch]
style = 'green'
truncation_length = 22
format = '[$branch]($style)'

[git_commit]
style = 'green'

[fill]
style = 'blue'
